name: practice-workflows-events
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master
jobs:
  pull-requestvalidation:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install depedencies
        run: npm ci
      - name: run  test
        run: npm tests
